version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    restart: unless-stopped
